google_sheet:
  google_sheet_link: "https://docs.google.com/spreadsheets/d/1BippKVFUFpa1KJRgK5qU2DDhl91SSKGcJsuMKxWf9PY/edit?gid=140354075#gid=140354075"
  google_sheet_subsheet_name: "Email Step 4"
  credentials_json: "credentials.json"
  block_list_subsheet_name: "block_list"

bounce_check:
  wait_seconds: 30

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"